---
name: postgres

networks:
  orglang:
    name: orglang
    external: false

services:
  storage:
    image: postgres:17.11-alpine3.24
    networks:
      - orglang
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DBA_USER
      POSTGRES_PASSWORD: $DBA_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      image.key: orglang/postgres

  database:
    image: orglang/pg-operator:latest
    networks:
      - orglang
    depends_on:
      storage:
        condition: service_healthy
    environment:
      DBA_URL: $DBA_URL
      DB_NAME: $DB_NAME
      DB_SCHEMA: $DB_SCHEMA
      OWNER_USER: $OWNER_USER
      OWNER_PASSWORD: $OWNER_PASSWORD
    entrypoint:
      - psql
    command:
      - "$DBA_URL"
      - -v
      - ON_ERROR_STOP=1
      - -v
      - DB_NAME=$DB_NAME
      - -v
      - DB_SCHEMA=$DB_SCHEMA
      - -v
      - OWNER_USER=$OWNER_USER
      - -v
      - OWNER_PASSWORD=$OWNER_PASSWORD
      - -f
      - /migrations/dba/bootstrap.sql
    labels:
      image.key: orglang/postgres

  schema:
    image: orglang/pg-operator:latest
    networks:
      - orglang
    depends_on:
      database:
        condition: service_completed_successfully
    environment:
      OWNER_URL: $OWNER_URL
    entrypoint:
      - migrate
    command:
      - -source
      - file:///migrations/owner
      - -database
      - "$OWNER_URL"
      - up
    labels:
      image.key: orglang/postgres
