---
name: Setup gear
description: Setup gear
runs:
  using: "composite"
  steps:
    - name: Setup go
      uses: actions/setup-go@v6.2.0
      with:
        go-version-file: engine/go.mod
        cache: true
        cache-dependency-path: |
          engine/go.sum
          sdk/go.sum
    - name: Setup task
      uses: go-task/setup-task@v1
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
